from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
from pathlib import Path
from datetime import datetime


def generate_ranking_pdf(job_title, company, rankings):
    output_dir = Path("exports")
    output_dir.mkdir(exist_ok=True)

    filename = f"candidate_ranking_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    file_path = output_dir / filename

    doc = SimpleDocTemplate(str(file_path), pagesize=A4)
    styles = getSampleStyleSheet()
    story = []

    story.append(Paragraph("TalentBridge - Candidate Ranking Report", styles["Title"]))
    story.append(Spacer(1, 12))

    story.append(Paragraph(f"<b>Job:</b> {job_title}", styles["Normal"]))
    story.append(Paragraph(f"<b>Company:</b> {company}", styles["Normal"]))
    story.append(Spacer(1, 16))

    data = [["Candidate", "Score", "Recommendation"]]

    for r in rankings:
        data.append([
            str(r.get("candidate_name", "")),
            str(r.get("ranking_score", "")),
            str(r.get("recommendation", ""))
        ])

    table = Table(data, colWidths=[140, 70, 280])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#185FA5")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("PADDING", (0, 0), (-1, -1), 8),
    ]))

    story.append(table)
    story.append(Spacer(1, 16))

    story.append(Paragraph("Generated by TalentBridge Recruitment Intelligence Platform", styles["Italic"]))

    doc.build(story)

    return str(file_path)